### ISSUE TITLE
Email sent twice

### ISSUE THREAD

**Issue by temporalmoebius** [p0ody/ff2ebook#1]
Issue:Email sent twice
Frequency:5/5 epub generated
Settings: fanfiction.net source, epub file, force update/auto download off, gmail account.

**Comment by p0ody** [comment]
Thanks for the detailled report, this has now been fixed.

**Comment by OilSubjectLoss7** [comment]
Dude can you make the old one again? This upgrade doesn't work. It's not working on mini browser and vice versa. Please. Dude revert it back. Sorry 4 my terrible english

**Comment by OilSubjectLoss7** [comment]
Thanks for the old version. :)
