### ISSUE TITLE
fictionhunt.com support

### ISSUE THREAD

**Issue by xzcvczx** [p0ody/ff2ebook#11]
Is there any chance of getting fictionhunt support?

thanks

**Comment by p0ody** [comment]
Hmmm, from what i can see on http://fictionhunt.com/, there is only fic links to fanfiction.net, so you could just copy the fanfiction.net link instead ?

**Comment by xzcvczx** [comment]
if you click on "Archived" instead of the name then its also on fictionhunt

an example story is seen http://fictionhunt.com/read/4292813/1
and while it is an archive of ff.net it also has stories that have been removed from ff.net

**Comment by p0ody** [comment]
Alright, try it out.  If you experience any issue, please create a new issue.
