### ISSUE TITLE
Search by date loaded

### ISSUE THREAD

**Issue by PhoenixFireOwl** [p0ody/ff2ebook#12]
I need to be able to sort by date of uploaded epub fanfiction files with title of story, not just input name of story. I may not (or don't) remember name of story i uploaded.

**Comment by p0ody** [comment]
Hi, I've added a dropdown menu on the archive page to allow to sort by: Title, author, updated date and source website. 

Its ugly AF but at this point i dont care enough to make it look decent haha.

**Comment by PhoenixFireOwl** [comment]
Thank you very much!
