### ISSUE TITLE
Content removal?

### ISSUE THREAD

**Issue by anon276304** [p0ody/ff2ebook#15]
Is there any way for an author to have their content removed from this archive? There is no way to contact the owner of this website to request this. Please respond.

**Comment by p0ody** [comment]
Contact me at mcliche91@gmail.com

**Comment by PhoenixFireOwl** [comment]
Sometimes, this is the only place I can find recommended stories.  It's too bad that they can be deleted. Can anyone delete a story or only the author? Hopefully, only the author can do that.

**Comment by p0ody** [comment]
So far only one author asked me to remove a story. So only that one should have been deleted.
