### ISSUE TITLE
Critical errors Not finding multiple chapters

### ISSUE THREAD

**Issue by PhoenixFireOwl** [p0ody/ff2ebook#17]
Still not able to download any ebooks on old, current or new sites. Critical errors, can't find chapter. Similar to issue #9. Even get error about can't find title name on newer version.

So far, all FF.net links not working for me.

Here's part of this issue's Critcal errors for https://www.fanfiction.net/s/12144422/83/The-Intelligent-Potter

Collecting Fiction infos...
Collecting chapters data...
Received chapter #1 data.
Critical Error: Couldn't find chapter(2) text.
Critical Error: Couldn't find chapter(3) text.
Received chapter #4 data.
Critical Error: Couldn't find chapter(6) text.
Critical Error: Couldn't find chapter(5) text.
Received chapter #7 data.
Received chapter #8 data.
Received chapter #9 data.
Critical Error: Couldn't find chapter(10) text.
Critical Error: Couldn't find chapter(11) text.
Received chapter #12 data.
Critical Error: Couldn't find chapter(13) text.
Received chapter #14 data.
Critical Error: Couldn't find chapter(15) text.

Can you help me? I even used different browsers. Thanks.

**Comment by StarWolf3000** [comment]
No need to open multiple similar issues.

@p0ody FF seems to have updated the HTML source for chapters, so it may take a while to get updated.

The script looks for:
```html
<div style='padding:5px 10px 5px 10px;' class='storycontent nocopy' id='storycontent' >chapter content</div>
```
while the recent HTML source is
```html
<div role='main' aria-label='story content' class='storytextp' id='storytextp'  align=center style='padding:0 0.5em 0 0.5em;'>
<div class='storytext xcontrast_txt nocopy' id='storytext'>chapter content</div>
</div>
```

**Comment by StarWolf3000** [comment]
Submitted a PR to address this issue: #18

**Comment by p0ody** [comment]
The preg_match was fine, it uses the mobile version of ff.net so thats why its not the same as what you found in the source.

You were right for the encoding though, thank for your help @StarWolf3000

**Comment by StarWolf3000** [comment]
I know this might be too much to ask, but could you enable the GZip support on the /old downloader too? I still prefer the epubs from that one over the newer one. If not, then I will use the new one.

**Comment by p0ody** [comment]
Have you tried it? I changed it at the same time and it worked when I tried
it earlier. Only the node version is currently not working Afaik

**Comment by StarWolf3000** [comment]
I tried it indeed a few minutes ago, and it worked, so nothing to do there :)
