### ISSUE TITLE
[Old site] Missing Fic Infos: Title

### ISSUE THREAD

**Issue by StarWolf3000** [p0ody/ff2ebook#19]
I have a problem with this fic:
https://www.fanfiction.net/s/12523795/1/A-Shattered-Reality

It used to work previously on the old interface, but now it spits out this error:
`MISSING FIC INFOS: TITLE`

However, it downloads if put into the newer inferface. This seems to be the only one so far, others still work on the the old site.

Edit on 04/07/2019: It is still random, on which fics it works and which not.

**Comment by derpyherp** [comment]
Same issue appears on reddit-ffn-bot links, e.g. `www.ff2ebook.com/old/ffn-bot/index.php?id=12523795&source=ff&filetype=epub`. Is it possible to build an URL like this for the new version of ff2ebook?

**Comment by p0ody** [comment]
Seems fixed, was an encoding error i think. i changed code to use curl.
