### ISSUE TITLE
book status on first page

### ISSUE THREAD

**Issue by xzcvczx** [p0ody/ff2ebook#2]
The first page of the book appears to have all the details except the status of the book In-Progree/Complete is it possible to add this?

Also the first page seems too squashed together vs what it was like the with p0ody-files version, any chance or something more similar to that?

Awesome service regardless, thanks

**Comment by p0ody** [comment]
I just added the status line on title page, it will appear only when the story is complete, if it doesn't appear, its either its not completed ro its from a site that doesnt show the status of the fic (Like harrypoterfanfiction.com)

See 7e13afa
