### ISSUE TITLE
Old Archive is Dead

### ISSUE THREAD

**Issue by Abject-Testament** [p0ody/ff2ebook#22]
Sorry I don't know how else to contact you. I apologize for intruding on your work, but 

http://ff2ebook.com/archive/old/ff_to_ebook_archive_2016-06-03.zip 

leads to a 404 Not Found page. I was searching Reddit and then I found that this link/file was supposedly an archive that contained a lot of dead/deleted fics and I really want to take a look. Could you restore the archive please?

**Comment by p0ody** [comment]
Im afraid I don't have that file anymore.  It was too big to keep on my webserver indefinitely (only 100GB available)  and i guess i formatted my PC since then, because i can't find the file.

Sorry
