### ISSUE TITLE
Hangs up on a certain book

### ISSUE THREAD

**Issue by CodeSpartan** [p0ody/ff2ebook#23]
Trying to download [this book](https://www.fictionpress.com/s/2961893/106/Mother-of-Learning) always hangs up on chapter 58.

**Comment by StarWolf3000** [comment]
Analyzing with the debug console in the browser, it appears that it cannot retrieve the text for a good chunk of the chapters (the following snippet is a portion of the response data):

```json
ficId: 2961893
chapNum: 72
error: []
```
```json
error: {…}
  code_2: 0
  message_2: Couldn't find chapter(75) text.
```

FictionPress parser needs to be adjusted?
