### ISSUE TITLE
Add documentation for self-hosting

### ISSUE THREAD

**Issue by dvingerh** [p0ody/ff2ebook#3]
Not a top priority or anything, but having simple setup instructions would be cool.
I already had changed the DB settings in sql.login.php but no dice.
Keeps throwing a ' Failed to get Fic Infos ' error at me and I can't figure out why.

**Comment by p0ody** [comment]
Might be missing the database tables.

I added the files to insert the table, see 1fc5645

**Comment by dvingerh** [comment]
The error still persists. I suspect it's some kind of restriction on my web host, but see below for console logs anyway:

A bunch of these when loading the webpage:
<img src="http://jawe.xyz/sharex/images/png/mD5aV.png">

And these when submitting the fanfiction:
<img src="http://jawe.xyz/sharex/images/png/R5xk2.png">

**Comment by p0ody** [comment]
Do you have php_curl module enabled ?

And if you have my .htaccess from this repo, delete it.

**Comment by dvingerh** [comment]
It seems to be enabled. Removed the .htaccess file, but now it won't fetch chapters.

I also tried running it locally using WAMP, but it won't even show the index page (gives me a 500 error). XAMPP also gets stuck at fetching the chapters. Same results on two different computers.

Console:
<img src="http://jawe.xyz/sharex/images/png/jmiFB.png">

**Comment by p0ody** [comment]
Which version of PHP are you running ?

**Comment by dvingerh** [comment]
5.5 (5.5.36 to be exact)

**Comment by p0ody** [comment]
hmmm, im running 5.5.12, so it shouldn't be a problem.

I tried cloning and moving everything in wamp and it works, so i dont know...

Is pdo_mysql module enabled ?
Heres my list of enabled php module in wamp if you want to make sure you have everything needed
![image](https://cloud.githubusercontent.com/assets/564032/16157965/f4303a42-3488-11e6-95e5-2c7b09436766.png)

**Comment by dvingerh** [comment]
Very interesting. I did a clean install of WAMP on my laptop (32-bits Apache : 2.4.9 MySQL : 5.6.17 PHP : 5.5.12 PHPMyAdmin : 4.1.14)
Set up the database, login settings and now it seems to work!
Still no such luck on my own web host though.

As I suspected the problem should probably be related to my own web host then. I'll try and fool around some more with the settings.

**Comment by dvingerh** [comment]
Alright, I mimicked the settings you showed me as best as I can on the host, and all is good now!
Thanks for the help bro. :+1:
