### ISSUE TITLE
I'm not able to download fanfics from fanfiction.net

### ISSUE THREAD

**Issue by Mel2814** [p0ody/ff2ebook#34]
Hi, I'm not able to download fanfics from fanfiction.net. Whenever I try, the following message appears in the Output tab: 
"Collecting Fiction infos...
Warning: Couldn't find title.
Warning: Couldn't find author.
Warning: Couldn't find fic type.
Warning: Couldn't find summary.
Warning: Couldn't find published date.
Warning: Couldn't find words count.
Warning: Couldn't find pairing (No pairing?).
Warning: Couldn't find fic fandom.
Collecting chapters data..."
Please help me.

**Comment by bastien8060** [comment]
Its a known issue. It has been discussed in #31 #30 #27, and #33.
