### ISSUE TITLE
Can't download from fictionpress.com

### ISSUE THREAD

**Issue by cherryglaserr** [p0ody/ff2ebook#36]
There used to be no problems at all. But, after fanfiction.com started having problems a few months back I couldn't download any stories from fictionpress. Now downloading from fanfiction is working fine, but I still unable to download from fictionpress. Any idea?

**Comment by StarWolf3000** [comment]
How can you download from fanfiction? It hasn't been working for 2 months now for me (basically since they implemented Cloudflare protection).

**Comment by cherryglaserr** [comment]
> 2

Oh shoot. It doesn't work again today. I swear a few days ago I just downloaded a fiction
![20210209_082516](https://user-images.githubusercontent.com/78750586/107302706-5c48df00-6ab0-11eb-87de-4c9dbabdfc5d.jpg)

**Comment by cherryglaserr** [comment]
> How can you download from fanfiction? It hasn't been working for 2 months now for me (basically since they implemented Cloudflare protection).

Oh shoot. It doesn't work again today. I downloaded a fic a few days ago and it worked just fine....strange 
![20210209_082516](https://user-images.githubusercontent.com/78750586/107302879-a29e3e00-6ab0-11eb-81a0-57662c72ede6.jpg)

**Comment by bastien8060** [comment]
I found a workaround, so this works for me! (FanFiction.net & FictionPress.com) 

Does this work for you? [https://ff2.theyoungappy.com/](https://ff2.theyoungappy.com/)

Edit: btw, if you wonder, there is no archive on this instance, so everything is taken from the source, so no cache or anything what so ever. Also I added Wattpad support on this, you just need the url with `/story/` in it.

**Comment by cherryglaserr** [comment]
> I found a workaround, so this works for me! (FanFiction.net & FictionPress.com)
> 
> Does this work for you? https://ff2.theyoungappy.com/
> 
> Edit: btw, if you wonder, there is no archive on this instance, so everything is taken from the source, so no cache or anything what so ever. Also I added Wattpad support on this, you just need the url with `/story/` in it.

Oh god, yes. It does work. Thank you so much! And it does support wattpad, thank you!

**Comment by bastien8060** [comment]
You're welcome! I'll just patch things up, because there are some security vulnerabilities. Not gonna tell which until its fixed :)

**Comment by cherryglaserr** [comment]
> You're welcome! I'll just patch things up, because there are some security vulnerabilities. Not gonna tell which until its fixed :)

Alright lol. Thanks tho, really appreciate it!

**Comment by bastien8060** [comment]
You can use it in the meantime, if you need ofc.

**Comment by cherryglaserr** [comment]
> You can use it in the meantime, if you need ofc.

Okay
