### ISSUE TITLE
Can’t download any fics

### ISSUE THREAD

**Issue by Louis123456789** [p0ody/ff2ebook#38]
I tried downloading some new fics and it got stuck at collecting chapters data and when I open the out put it says

Warning: couldn't find title
Warning: couldn't find author
Warning: couldn't find fic type
Warning: couldn't find summary 
Warning: couldn't find published date
Warning: couldn't find words count
Pairing (no pairing?)
Warning: couldn't find fic fandom
Collecting chapters data

**Comment by bastien8060** [comment]
see #37 #34 #31 #30 and #27.
