### ISSUE TITLE
Wattpad

### ISSUE THREAD

**Issue by crusheidi** [p0ody/ff2ebook#39]
To download Spanish on wattpad, the accents don't come out. (ñ á ā é í ó ú¡ 
![Screenshot_20210225-130535](https://user-images.githubusercontent.com/79662189/109203786-31c27b80-776a-11eb-95ef-39ce4d65b7f8.png)
¿)

**Comment by bastien8060** [comment]
This is an issue I haven't had time to track down. I think I guessed where it might come from, however, I might be wrong. I will look into it this weekend.

**Comment by bastien8060** [comment]
Which url do you use btw? I dont have access to FF2Ebook.com  Only P0ody has I think. I can access nd modify https://ff2.theyoungappy.com though. Be mindful that the last one is only a test environment. Try http://ff2ebook.com/pr32

**Comment by crusheidi** [comment]
I use this http://ff2.theyoungappy.com/ this one has for wattpad.

**Comment by bastien8060** [comment]
Ok i'll look into it tomorrow
