### ISSUE TITLE
won't download from ffn again.

### ISSUE THREAD

**Issue by LanzCorporalAssWipe** [p0ody/ff2ebook#40]
The site isnt working for ffn again.
![Screenshot_20210505-083555_Firefox](https://user-images.githubusercontent.com/75571256/117085533-ac1c0700-ad7c-11eb-8f06-d99511e71c57.jpg)
It started yesterday. Around the afternoon or near evening i think. Philippine time.

**Comment by StarWolf3000** [comment]
I've been experiencing issues too, maybe @bastien8060 is already aware of this?

**Comment by bastien8060** [comment]
@LanzCorporalAssWipe  Indeed, maybe my ip was banned or they found a workaround? You can try again/later. If my server ip is banned, you can try tomorrow when it will be unbanned. 

@StarWolf3000 I have just recently heard of flairsolverr which is more stable than cloudscraper. Many website like fanfiction websites use it daily and are benefiting from it. I will implement it maybe in the weekend if I have time. It's a docker image though, which requires root access (at least to install docker IIRC). I can do that though on my new server.

**Comment by bastien8060** [comment]
https://github.com/FlareSolverr/FlareSolverr

**Comment by bastien8060** [comment]
Edit: it seems that docker can be installed without root actually, though it is not officially supported:
https://www.docker.com/blog/experimenting-with-rootless-docker/

**Comment by LanzCorporalAssWipe** [comment]
Yup. It's down again.
![Screenshot_20210518-112912_Firefox](https://user-images.githubusercontent.com/75571256/118585959-763f3f80-b7cc-11eb-8e54-5aebe40b9198.jpg)

This time it just says can't find fic.

**Comment by bastien8060** [comment]
Maybe the ip was banned, you can try again later, there isn't much otherwise

**Comment by StarWolf3000** [comment]
Can't you check your logs for the server response from FFN?

(I'm getting this error too, since it was reported 2 days ago.)

**Comment by bastien8060** [comment]
Okay, I will do so tonight. Main thing is I need to finish a thesis in history, and then I'm free. It's actually my last day today

**Comment by bastien8060** [comment]
Sorry, I know it was a lazy answer, sort of. 
> Maybe the ip was banned, you can try again later, there isn't much otherwise

**Comment by StarWolf3000** [comment]
Any news on that end?

**Comment by bastien8060** [comment]
@StarWolf3000 @LanzCorporalAssWipe

Sorry totally forgot to go back to you guys. So I did actually make many tests, but these were not very helpful. It did turn out to be cloudflare that banned my IP for a start. (can tell because it wont download even from curl). Then also they updated their stuff on their side, so I will attempt at some point to update my end to have FicSolverr to work. Finally I accidentally had removed a package which depended on python3.6 so I needed to reinstall it.

Another weird stuff. I made a fork long time ago of ff2ebook, and made a redesign + reworked everything to make it better, however, for this one, requests don't even go through in the dev tools.

Anyways, bought another IP + fixed it, so it re-works :)

**Comment by bastien8060** [comment]
tested the fix here: https://ff2.theyoungappy.com/

**Comment by StarWolf3000** [comment]
So it's basically the usual cat-and-mouse game.

**Comment by bastien8060** [comment]
Exactly, but some guys at fichub.net told me that them, being the 'mouse' hadn't had the need to do any maintenance related to cloudflare with ficsolverr

**Comment by bastien8060** [comment]
Also, you know what? I have 55mins left of some free time, before I need to get going, so I will try to get it working now. Expect downtime lol.

**Comment by bastien8060** [comment]
Sorry not ficsolver, meant flaresolver

**Comment by NightMachinery** [comment]
@bastien8060 Did you install https://github.com/FlareSolverr/FlareSolverr after all?

**Comment by StarWolf3000** [comment]
I've been wondering about that too, since recently I've been experiencing problems with sometimes not all chapters being retrieved. First telling me that there's no chapter text on some and trying the second time taking too long to actually fetch other chapters without properly timing out.

**Comment by bastien8060** [comment]
Sorry was away for the week. Nope didn't because my fast dedicated server doesn't let me root access to install docker. My second server performance wise won't be enough (2 slow cores / 4very slow threads)

**Comment by them1ghtydill** [comment]
Downloading from ffn doesn't work; not sure if this should be on the same issue or not because my problem is different. It finds the fic and everything, goes through the process and when it's supposed to download it directs me to a page that says "File not found on server,". Not sure if it is for other websites as well or not. @bastien8060 is this only an issue for me?... Thx

**Comment by bastien8060** [comment]
This is a known bug that has been known to me. It doesn’t affect ff2ebook’a default branch, but I use a special branch that doesn’t require a database. However, a bug comes with it, so when you try downloading a story to mobi, it will fail like you described. 

Easy fix? Just change to ePub and use an online converter to convert it to mobi.

**Comment by bastien8060** [comment]
Or if you are using ePub already, this could be a different issue.

It could be just timing. The ebook's filename is based on the datetime (something like `fanficname`_`hh-mm-ss`.epub) . That means that if you download it at a different minute, then it will look for a different filename that doesn't exist. 

If you were unlucky, you converted the story at xx-xx-59 (hh-mm-ss), and one second later the file couldn't be found anymore.

**Comment by bastien8060** [comment]
@them1ghtydill with my replies above, feel free to send a reply back if you fixed it.

... If you didn't, can you give me further information (console screenshot in inspect element/browser name and version/ etc...)
