### ISSUE TITLE
Problem with some Wattpad stories

### ISSUE THREAD

**Issue by AkiraReader** [p0ody/ff2ebook#42]
Hello, sorry to bother you, but I keep having downloading problems with stories that have their title with an acute accent ("´") mark in wattpad as I always get "Critical Error: Failed to get Fic Infos, please try again later."

For example:
https://www.wattpad.com/story/207780874-dxd-camino-hacia-la-dominaci%C3%B3n
https://www.wattpad.com/story/117689761-el-nuevo-dios-drag%C3%B3n

**Comment by bastien8060** [comment]
I won't have time to fix this any time soon unfortunately. This is a known bug though. I'm going to be busy in around this month.

Though maybe somebody could help and could submit a merge request. I'm sure the bug has to do with the way the temporary information are saved with PHP.

**Comment by bastien8060** [comment]
While I made quite some effort to fix fanfiction.net on ff2ebook and add features, it is to note I don't own the project either though I'm happy to help when I can :) !
