### ISSUE TITLE
FF.net changed url schema ?

### ISSUE THREAD

**Issue by obrhubr** [p0ody/ff2ebook#43]
Hi,

I am not sure if either @bastien8060 or @p0ody still look at any issues on this or if they abandoned the project, but I wanted to submit this issue anyway.

I am not very good at php nor am I familiar with the codebase and I might be very wrong.

I think a problem with downloading ff.net books might be that they changed the way to access chapters from `/title/chapter` to `/chapter/title`.

**Comment by StarWolf3000** [comment]
The URL schema has been like that for a long time, so nothing has changed.

**Comment by obrhubr** [comment]
Yeah I realised that pretty much immediately after, that's why I closed the issue that quickly. That's on me for doing things without thinking first :(.

But thank you for confirming!

**Comment by bastien8060** [comment]
Don't worry ;)

Edit: sorry not checking often my github, so sorry for delay I guess
