### ISSUE TITLE
Hangs while collecting data - FFN

### ISSUE THREAD

**Issue by DanYHKim** [p0ody/ff2ebook#44]
Attempting FFN conversion and download. Progress bar moves a bit, then stops forever.
Output:
Output: (Click to toggle)
Collecting Fiction infos...
Warning: Couldn't find title.
Warning: Couldn't find author.
Warning: Couldn't find fic type.
Warning: Couldn't find summary.
Warning: Couldn't find published date.
Warning: Couldn't find words count.
Warning: Couldn't find pairing (No pairing?).
Warning: Couldn't find fic fandom.
Collecting chapters data...

Previously, this output would show, but a .mobi ebook would still be generated. 
I am careful to make sure the fanfic link is for the first chapter, if that is of significance.

EDIT: I notice that my browser (Firefox 91.0.2 (64-bit) for Windows ) shows the ff23book site to be "not secure". This is not solved by explicitly prepending "https . . . " to the URL. This might be what makes it hang.

**Comment by StarWolf3000** [comment]
It doesn't look like the "original" site is being worked on in the foreseeable future, so there's a fork on another site which used to work until 2 days ago.
