### ISSUE TITLE
Site down?

### ISSUE THREAD

**Issue by LanzCorporalAssWipe** [p0ody/ff2ebook#45]
The site seems to be down. Why? Maintenance?
The site was finally working last night(Philippine Time, i dont know how to translate that to pacific standard or tine zones) around 11pm ish up till 2 or 3am then stopped working again.

**Comment by Undercover487** [comment]
Thought I was the only one having this problem.. Any idea what's the issue??

**Comment by StarWolf3000** [comment]
Don't know what happened, but I'm notifing @bastien8060 of this (yes, your domain with the improved fork, not the "original" ff2ebook).

**Comment by bastien8060** [comment]
Sh*t! Many thanks for that! I forgot to renew my domain name! If you want, I can "buy" one of these sketchy domain name in the meantime (.tk domain name) cause rebuying my other domain name will take a bit of time...

**Comment by bastien8060** [comment]
I'll be back in a bit with more info

**Comment by bastien8060** [comment]
@LanzCorporalAssWipe @StarWolf3000 @Undercover487 It's back...! 

...but on a different URL

In the meantime, this will be the URL: https://ff2ebook.tk

Https cert isn't ready yet... And I'm also trying to renew the other domain name and get it back :(.

Sorry for that. 

The positive note is: since there are less people aware of the new domain name, its going to work quicker/more reliably perhaps...?

**Comment by bastien8060** [comment]
Also DNS propagation might take a while. If the link doesn't work try clearing DNS cache or changing DNS server to `8.8.8.8`.

Edit: Https certs are finished and finally installed -> Safer browsing (though I don't really think you'd lose much without it anyway)

**Comment by StarWolf3000** [comment]
I can access the site just fine, just generating an ebook doesn't seem to work (stuck at "Collecting infos"). I'm on mobile Chrome, so I can't check the console, but maybe it's a CORS issue?

**Comment by bastien8060** [comment]
Damn I'm on mobile too.. did the sysadmin + domain name stuff on my phone... 

I'm currently away from my laptop, so I'll try that app I used to know on the play store that has a js console

**Comment by bastien8060** [comment]
Perhaps my servers IP got banned by CF also? :(

It's always been the thing I feared

**Comment by bastien8060** [comment]
@StarWolf3000 I have no errors in my console. It's timing out.

I had a similar issue in the past so:
I think this is an issue with my host provider. I use two server one of which is dedicated with root, and another isn't. The latter which hosts ff2ebook fork had a bunch of issues where MySQL was breaking PHP's sessions storage. I'll email them tmro (it's late here) and check back.

**Comment by LanzCorporalAssWipe** [comment]
Im on the phone browser too so i cant do anything 😭. I hope you get it compatible for phone browsers soon.

**Comment by StarWolf3000** [comment]
Hi, it's working now. It took a while until my browser accepted the certificate, as each attempt yesterday resulted in unsecured https (maybe that was the issue on my side?).

**Comment by LanzCorporalAssWipe** [comment]
Its not downloading for ffn 😭 stuck in collecting chapters

**Comment by PhoenixFireOwl** [comment]
The new link doesn't work for me. It hangs and doesn't go past 'collecting
infos' even after múltiple attempts.

Sorry.

**Comment by StarWolf3000** [comment]
It does 2 requests, the first is an XHR GET request to https://ff2ebook.tk/ajaxPHP/ajax.getCookies.php and the second an XHR GET to https://ff2ebook.tk/ajaxPHP/ajax.saveCookies.php
Nothing happens after that, so I guess there's some issue with the session management.

**Comment by bastien8060** [comment]
I'll take a look at it

**Comment by LanzCorporalAssWipe** [comment]
Is stuck on collecting again. Or collecting failed

**Comment by StarWolf3000** [comment]
Any feedback on this @bastien8060?

**Comment by Undercover487** [comment]
Hey guys considering that the site is down right now try this link it seem to be working, I have no idea how they are doing it. 
But there are some issues I am not able to manually update the files when the fic on ff updates. 

https://fichub.net/

thought it might help, they are on 
https://github.com/FicHub/fichub.net

*link changed. 

Thanks @StarWolf3000

**Comment by StarWolf3000** [comment]
@Undercover487 I've been using that one for a fic which worked and a second one, but the second one probably was already cached, so instead of the most recent one I got a copy from half a year ago. It's not really difficult to implement an update check, at least for FFN, as the site itself posts the update time public, so you just have to parse it and compare to the timestamp of the cached version and then retrieve it and update the cache.

Also for some reason your link to the GH repo is wrong, it should be https://github.com/FicHub/fichub.net

**Comment by iridescent-beacon** [comment]
@StarWolf3000 half a year is quite a long time! Do you happen to remember which fic it was?

@bastien8060 this seems like it may just be a free time issue, but let me know if you want help debugging something :)

**Comment by StarWolf3000** [comment]
@iridescent-beacon This one: https://www.fanfiction.net/s/13315856/1/Hyperdimension-Neptunia-One-Shots

The last fic update of this one I have is from 31st of August 2021.

**Comment by bastien8060** [comment]
@iridescent-beacon Hey sorry! Indeed school is taking too much time off me. My dedication to calculus and American history is too deep, yet loathed and needed. I'll send you the repo in an hour if you want to have a look!

**Comment by bastien8060** [comment]
Thanks btw

**Comment by iridescent-beacon** [comment]
@StarWolf3000 ah, the author marked it as complete a long time ago and just keeps adding chapters to it. Probably need some kind of list for fics that say they're complete but aren't really. The last couple of chapters are showing in fichub now.

@bastien8060 it happens :)  is it running a specific commit of your fork, or something that isn't pushed currently?

**Comment by bastien8060** [comment]
It's running the latest commit of my fork with few changes added which I'll commit now. I do have many different forks including one with a beta redesign. I'll send you the one which is pushed live.

**Comment by bastien8060** [comment]
Here it is: https://github.com/bastien8060/ff2ebook/tree/portable 

Sorry for not being able to look into much btw. I might be able at some point. It's the portable branch also.

**Comment by p0ody** [comment]
I know this issue was talking about @bastien8060  fork, but you can check ff2ebook.com.  I got fanfiction working with selenium (it is slow though)
