### ISSUE TITLE
Fanfiction.net stories not downloafing

### ISSUE THREAD

**Issue by kolbdog3333** [p0ody/ff2ebook#47]
When trying to download fanfiction.net stories it goes though all 5 proxies but doesnt download there is errror

**Comment by Undercover487** [comment]
Having the same issue. But only when I try to force update the fics. The site is able to access the archive without any issue.

**Comment by StarWolf3000** [comment]
I have experienced the same issue. Though I have to use the "Force update" to get the most recent versions of updated fanfics, because I have the cached versions already.

**Comment by p0ody** [comment]
Seems to be cloudflare being a pain again....  I'll try to get it working again when i get the time

**Comment by LanzCorporalAssWipe** [comment]
Any update on the fix? I'm getting this gut feeling that theres gonna be another purge on FFN. It might be nothing but better safe than sorry. I need to save the LEMONS.

**Comment by p0ody** [comment]
Check out ff2ebook.com, it is back to working.

**Comment by StarWolf3000** [comment]
Working for now, but this "glitch" was funny :)
![Screenshot_20211122-185512](https://user-images.githubusercontent.com/787808/142912331-ed67e5ed-d766-47d9-bac1-3f07aabc6a76.png)

**Comment by p0ody** [comment]
@StarWolf3000 damn... hahaha, i'll check into that when i got the time lol

**Comment by LanzCorporalAssWipe** [comment]
Goddamnit not working again. Fucking ffn. Why in the fuck did they have to put that captcha shit anyway? One minute im reading a chapter then going to the next chapter another fucking captcha. Just why????

**Comment by p0ody** [comment]
@LanzCorporalAssWipe Sorry, that might have been my bad, i changed something earlier on my webscraper server and the process fetching fanfiction.net was down.  I just restarted it, should be good.

**Comment by LanzCorporalAssWipe** [comment]
Yup. Its up again. Thanks! For a second there I thought ffn was being a pain in the ass again.

**Comment by StarWolf3000** [comment]
Well they are (or CF in this case). It seems it's blocked again.

**Comment by p0ody** [comment]
seems like my solution isn't as stable as i'd hoped.  I'm currently redirecting the request to my own PC, and it seems there is a bottleneck somewhere slowing everything down.  I guess its the node module Pupflare, or maybe my ISP.

Right now it is working, albeit slowly.

**Comment by p0ody** [comment]
I think i have something running that is somewhat stable.  We will see with time...

**Comment by kolbdog3333** [comment]
It seems not working again it stopped working yesterday.

**Comment by StarWolf3000** [comment]
It didn't work yesterday (haven't tried the day before and in general not very often recently, due to authors not updating what is interesting for me), but today seems to work, just generated this "monstrosity" with 145 chapters:
![Screenshot_20211212-190906](https://user-images.githubusercontent.com/787808/145724275-15fe9054-c674-4e45-8aae-77ddaa1c4b41.png)

**Comment by p0ody** [comment]
Sorry, i was moving so my old pc that i use as webscraper wasn't connected.

**Comment by kolbdog3333** [comment]
Looks like ff2ebook force update is down again.

**Comment by p0ody** [comment]
I just restarted the scraper service, it seems to be back to working.

Thanks for the heads up

**Comment by kolbdog3333** [comment]
No problem.

**Comment by kolbdog3333** [comment]
force update just went down a few minutes ago

**Comment by kolbdog3333** [comment]
force update just went down a few minutes ago again

**Comment by kolbdog3333** [comment]
force update is down

**Comment by kolbdog3333** [comment]
never mind

**Comment by StarWolf3000** [comment]
@kolbdog3333 It might take a while sometimes

**Comment by kolbdog3333** [comment]
force update is down been trying for half hour nothing

**Comment by kolbdog3333** [comment]
force update is down

**Comment by kolbdog3333** [comment]
it stuck on collecting chapter data

**Comment by kolbdog3333** [comment]
force update is down not gathering any chapters it says retrying for all chapters

**Comment by kolbdog3333** [comment]
force update is down not gathering any chapters it says retrying for all chapters

**Comment by kolbdog3333** [comment]
force update been down for an hour now

**Comment by kolbdog3333** [comment]
automatically goes to collecting chapter data and stuck there just says retrying all chapters goes through each one

**Comment by StarWolf3000** [comment]
Worked for me when you posted this.

**Comment by kolbdog3333** [comment]
force update is down and has been having problems last couple days it works for 1 or 2 fanfics stops then works again after 15 minutes

**Comment by kolbdog3333** [comment]
force update down since 8:30 AM this morning

**Comment by kolbdog3333** [comment]
force update down since 9:30am on both sites

**Comment by kolbdog3333** [comment]
still down

**Comment by kolbdog3333** [comment]
force update still not working hasnt been since this morning

**Comment by kolbdog3333** [comment]
still down

**Comment by kolbdog3333** [comment]
force update still not working hasn't been since yesterday morning

**Comment by p0ody** [comment]
Yes i looked into it yesterday and everything is running right, but i think cloudflare made a slight change or something, because it doesn't work anymore for now.  I haven't had the time yet to fix it, i'll look more into it tonight.

Sorry

**Comment by kolbdog3333** [comment]
some stories will download others wont

**Comment by kolbdog3333** [comment]
Also thanks hope have it fixed since force update just went down at 11:30am

**Comment by p0ody** [comment]
@kolbdog3333 Yeah i was playing around to try and fix it, so it kinda worked sometimes and then i screwed up something else lol.

I think i got it working properly now

**Comment by kolbdog3333** [comment]
yeah its working now.
Im glad you created this site it works better than fanficfare for fanfiction.net and fictionpress

**Comment by kolbdog3333** [comment]
force update is down
