### ISSUE TITLE
Server down?

### ISSUE THREAD

**Issue by AkiraReader** [p0ody/ff2ebook#53]
When I enter https://ff2ebook.tk/ to download from wattpad, I get this message: 

The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

Additionally, a 503 Service Unavailable error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by StarWolf3000** [comment]
It is https://www.ff2ebook.com

**Comment by AkiraReader** [comment]
That one only downloads from fanfiction, the other one until 2 or 3 days ago did from wattpad

**Comment by kolbdog3333** [comment]
Tried downloading from fanfiction.net on ff2ebook.com but server is down

**Comment by AkiraReader** [comment]
Well, since a day ago https://ff2ebook.tk/ has been working again.

**Comment by kolbdog3333** [comment]
When will ff2ebook.com be back up and running?

**Comment by p0ody** [comment]
I dont know why it is not currently working.

For the moment you can try on http://maxcli.dreamhosters.com/ .seems to be working for me on this address but not on ff2ebook.com. (Might be a problem with my domain)

**Comment by StarWolf3000** [comment]
It seems back online.

**Comment by kolbdog3333** [comment]
just saw thanks
