### ISSUE TITLE
fanfic download problem

### ISSUE THREAD

**Issue by kolbdog3333** [p0ody/ff2ebook#57]
Am trying to download fanfics from fanfiction.net and it stops at 4 chapters. And even though server is up takes about 20 force updates for the the fanfic to download properly.

**Comment by kolbdog3333** [comment]
Still trying it says webscraper server is up and running. But no chapters download and it stops at 4 chapters when using force update.
Please fix.

**Comment by p0ody** [comment]
Could you give me the link to the fic you are trying, seems to be working fine when i try it,

Thanks

**Comment by kolbdog3333** [comment]
Its any fanfic here are two am trying get. using force update doesngt seem to work
 https://www.fanfiction.net/s/13626213/105/I-Don-t-Run-An-Orphanage
         https://www.fanfiction.net/s/14004915/51/School-opens-part-one"

**Comment by kolbdog3333** [comment]
Now its stopping at this
Collecting Fiction infos...
Warning: Couldn't find fic type.
No attempting at all or collecting chapter data

**Comment by kolbdog3333** [comment]
Collecting Fiction infos...
Warning: Failed to get Fic Infos (Attempt 2/5), attempting again.
Stops at 2/5

**Comment by StarWolf3000** [comment]
Yeah for some reason it stops with the red error symbol, but without writing any error in the log below.
![image](https://user-images.githubusercontent.com/787808/159971240-bf92e623-2776-4eb4-835f-09187b289501.png)
And in the JS console it throws an error at line 46 in functions.js:
```
Uncaught Error: An error has occured and the script has been stopped.
    at changeState (functions.js:46)
    at newError (errorHandler20220324.js:45)
    at ajax_getFicInfos (ajax.functions20220324.js:69)
    at Object.<anonymous> (ajax.functions20220324.js:129)
    at i (jquery-1.12.4.min.js:2)
    at Object.fireWith [as rejectWith] (jquery-1.12.4.min.js:2)
    at y (jquery-1.12.4.min.js:4)
    at XMLHttpRequest.c (jquery-1.12.4.min.js:4)
```

**Comment by kolbdog3333** [comment]
Will you be able to fix it

**Comment by p0ody** [comment]
Ok i think i fixed it, give it a try. (Dont forget to refresh the page)

Earlier i added a new error type for blacklisted fic/author and i thing i somewhat broke the error handling.

**Comment by kolbdog3333** [comment]
Its fixed thank you very much appreciate it.
