### ISSUE TITLE
Can’t collect info 

### ISSUE THREAD

**Issue by tetra59** [p0ody/ff2ebook#74]
It could be cloudflare screwing up the ffnet site again because it’s been requiring captchas an awful lot but today your site won’t go past getting the fic info. Do you think you might be able to fix it or are you fed up with ffnet glitching? Thx

**Comment by p0ody** [comment]
Thanks for the report, i just had to add a new check in the cloudflare bypass for the new cloudflare page.

Should be fixed

https://github.com/p0ody/ff2ebook-cloudflare-scraper/commit/6ee68a81deb6a743af874deb37a20c998487dcb5
