### ISSUE TITLE
Site error: 503 Service Unavailable

### ISSUE THREAD

**Issue by StarWolf3000** [p0ody/ff2ebook#86]
Seems like the server encountered issues processing the site, probably some hanging services/daemons. Tried to restart the site?

**Comment by p0ody** [comment]
Seems to be a problem with the domain or SSL certificate, dont know what to do with it except wait.

You can try out http://maxcli.dreamhosters.com/ in the mean time (Default domain from my host), it seems to work

**Comment by StarWolf3000** [comment]
That doesn't work with the way your scripts work, it instantly fails to communicate with the backend (warnings retrying 1 to 5 and then immediately stops).

**Comment by p0ody** [comment]
ok lmao, its weird but you can use http://www.deploy.ff2ebook.com/
Its supposed to be the same code as the other url i gave you but it seems to work

**Comment by StarWolf3000** [comment]
OK, so while that deploy URL would not crash, it would only create the title page for the fic, while still telling us it retrieved all chapters too, but wouldn't put them in the file. For whatever reason the main URL seems to work again now, and it worked in fully processing the fic.
