### ISSUE TITLE
[FF.net] Unknown issue receiving chapter data (old and new converters)

### ISSUE THREAD

**Issue by StarWolf3000** [p0ody/ff2ebook#9]
As of today I can't create any new ebooks from FF.net. It retrieves a large number of chapters and fails to  fetch the rest, even after attempting to refetch. With the new converter, it stops at `Warning: Failed to get chapter #anynumber (Attempt 2/3), attempting again.` and the old mobile just prints `error CHAPTER INFOS: GET CONTENT`.

**Comment by p0ody** [comment]
Hey, can you add the link to the fic that you are trying to convert ?

**Comment by StarWolf3000** [comment]
It was no specific one, not a single one worked, but later it worked again. Maybe it was just a temporary issue, either with your server or with ff.net.

**Comment by PhoenixFireOwl** [comment]
I'm getting similar issue. I still can't download ebooks due to 2 issues. One of them is this one. 

https://www.fanfiction.net/s/12144422/83/The-Intelligent-Potter
