### ISSUE TITLE
Both servers down 

### ISSUE THREAD

**Issue by tetra59** [p0ody/ff2ebook#94]
Don’t know if it’s weather on your end or maybe you’re luckily on vacation instead of stuck at home but both servers are down. Thx.

**Comment by p0ody** [comment]
I've restarted both servers this morning before going to work and they both seems to not be workiing so im guessing a change on cloudflare side again.  I'll take a look when i can.

Thanks

**Comment by p0ody** [comment]
Yep, as i said, the cloudflare captcha changed again.   both servers should be updated and back up

Thanks
